version: "3.9"
services:
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - type: volume
        source: data
        target: /data/db
    environment:
      MONGO_INITDB_DATABASE: "${DB_NAME}"
      MONGO_INITDB_ROOT_USERNAME: "${DB_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD}"
    command: --quiet
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo ${DB_HOST}:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s
    ports:
      - 8002:${DB_PORT}

  server:
    build:
      context: ./server
    expose:
      - ${SERVER_PORT}
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - SERVER_HOST
      - FLASK_PORT
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_PORT
      - SPOTIFY_CLIENT_ID
      - SPOTIFY_CLIENT_SECRET
      - FLASK_SECRET
    ports:
      - ${SERVER_PORT}:${FLASK_PORT}

  web:
    build: 
      context: ./web
      args:
        API_SERVER: ${API_SERVER}
        AUTH_SERVER: ${AUTH_SERVER}
        HOMEPAGE: ${HOMEPAGE}
    ports:
      - ${WEB_PORT}:80
    depends_on:
      - "server"

volumes:
  data:
