- hosts: control-1
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_task

    - name: set join command as a fact
      set_fact:
        join_command: "{{ join_command_task.stdout_lines[0] }}"

- hosts: nodes
  become: yes
  tasks:
    - name: join the cluster
      shell: "{{ hostvars['control-1'].join_command }} >node_joined.txt || rm node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt
