- hosts: control-1
  tasks:
    - name: copy the resolved k8s files
      synchronize:
        src: proxy-service.yml
        dest: /home/ubuntu
        archive: no
        recursive: yes

    - name: deploy proxy service
      shell: "kubectl apply -f ~/proxy-service.yml"
